### ISSUE TITLE
Should we have a seperate discord

### ISSUE THREAD

**Issue by Benjmhart** [input-output-hk/Developer-Experience-working-group#14]
currently the iohk discord is very crowded and the registration steps necessary create a lot of barrier to entry for developers getting involved with the working group.  i suggest we use the CIP editors as an example and move to a seperate server,  which we can use for discord-based meetings and agenda management.

**Comment by manonthemat** [comment]
As we have moved to the **Working Groups** discord server, I propose to close this issue.

**Comment by anitajov** [comment]
Thank you @manonthemat I will close this issue as we opened the separate Discord Server for Working Groups.
