### ISSUE TITLE
Open Source End-to-End examples of Plutus dApps

### ISSUE THREAD

**Issue by Benjmhart** [input-output-hk/Developer-Experience-working-group#22]
There has been some discussion about open source example dApps - especially as templates that can be forked and used by developers to write something quickly. 

These serve as examples of best practices, code organization, and also help the user overcome the host of problems that can arise when trying to assemble individual tools into a working dApp.  

Some existing e2e example dApps:
- [Seabug](https://github.com/mlabs-haskell/seabug)
- [cardano-marketplace](https://github.com/dQuadrant/cardano-marketplace)

Other open source Smart contracts users can use as examples:
- [jpeg store contracts](https://github.com/jpg-store/current-jpg-store-contracts)

**Comment by AlainMgz** [comment]
Hey, just want add a couple of things to your comment :)

First of all, a small correction: the jpg contract you are displaying is a fork of a contract made by Martify Labs, so we would appreciate referring to the original contract source (You can see that I'm the author in the vendere.cabal file :)): [Martify Marketplace Contract](https://github.com/MartifyLabs/martify.contracts)

Then let's add some more open source resources:
- Martify Labs open sourced its entire [marketplace e2e](https://github.com/MartifyLabs/martify.frontend) several months ago
- We also provide a repository containing several plutus smart contracts for various use cases where everyone can contribute: [mesh.plutus](https://github.com/MartifyLabs/mesh.plutus)

Hope this discussion continues and we add more and more open source projects on Cardano!

**Comment by Benjmhart** [comment]
@AlainMgz - thanks so much for the clarification!

**Comment by aleeusgr** [comment]
I hallucinate bits and pieces of piggy bank dApp based on plutus-starter, any sponsorship is welcome.
Harry is building flake.nix for plutus starter, I am assuming submissive posture and feel like covid.

**Comment by aleeusgr** [comment]
https://github.com/joinplank/cardano-e2e-example

**Comment by aleeusgr** [comment]
https://github.com/OpShin/opshin-starter-kit

- [ ] add potential robot

**Comment by klarkc** [comment]
Templates: https://github.com/LovelaceAcademy/nix-templates (nix, plutus and cardano-tx-lib)
They are being used in: https://github.com/LovelaceAcademy/PlutusExperience

**Comment by manugunther** [comment]
> https://github.com/joinplank/cardano-e2e-example

A complete tutorial based on that example is available here:
https://cardano-e2e-example.readthedocs.io/en/latest/index.html

The dApp example is live on preprod here:
http://escrow.joinplank.com:3000/

Video introduction:
https://youtu.be/UzdabJ5XpIo

**Comment by aleeusgr** [comment]
https://meshjs.dev/
TODO?: add link to Gimbalabs Youtube, Jan 30 Playground MeshJS presentation

**Comment by aleeusgr** [comment]
This looks like a good candidate for a wiki page, so I moved the info there:
https://github.com/input-output-hk/Developer-Experience-working-group/wiki/Open-Source-e2e-examples
