### ISSUE TITLE
Nix pedagogy (in Cardano context) is woefully lacking but dropping Nix is not the answer

### ISSUE THREAD

**Issue by harryprayiv** [input-output-hk/Developer-Experience-working-group#54]
### PLEASE don't drop support for nix.  

Hearing rumors that IOG is considering deprecating their Nix support.  I just want to put my vote in that I will be dropping out of the Cardano ecosystem altogether if that's the case.  Cardano is tough enough as it is..but Nix makes everything easier once you understand it.  The problem with using nix in this ecosystem is not Nix.  **It is the lack of documentation around Cardano's use of nix which I am working independently to rectify.**

**Comment by disassembler** [comment]
Let me put people minds at ease, these rumors are not true. We have no intention of dropping nix support.

**Comment by harryprayiv** [comment]
> Let me put people minds at ease, these rumors are not true. We have no intention of dropping nix support.

Happy to hear it.  Nix may have its problems but I have fallen in love with it the past six months.  :)

**Comment by blaggacao** [comment]
I'm in the process of doubling down on adoption of [Standard](https://std.divnix.com/) in the projects where I have stake & responsibility.

> may have its problems

Let's fix them! :smile:

**Comment by aleeusgr** [comment]
Not to stop anyone from using it, but the name STD isn't very helpful to adoption.

[Screenshot_from_2023-02-20_13-57-06-2.png](https://user-images.githubusercontent.com/36756030/220628675-e61b7b4d-4e1d-4caf-986c-68921cb1620b.png)

**Comment by blaggacao** [comment]
First steps have actually just been taken. One can now for example install & type `paisano`, instead.

https://paisano-nix.github.io/tui/
