### ISSUE TITLE
discuss the developer ecosystem survey

### ISSUE THREAD

**Issue by aleeusgr** [input-output-hk/Developer-Experience-working-group#76]
https://cardano-foundation.github.io/state-of-the-developer-ecosystem/2023/

**Comment by aleeusgr** [comment]
26. What do you think is the most painful point of Cardano's developer ecosystem?

Peter MLabs: 
this should have been ranked choice imo. I don't think this is a very useful way to represent this data
I still think that rating each item by their severity will give us more useful information.
WRT to ranking (vs rating) I can say that for me, there's 4 things on that list that I care about at all as a developer; the rest I would rank in arbitrary order 

I don't disagree that smaller teams can accomplish things that larger teams can't, but I don't think that that the question here is "large teams" or "small teams". I think the question (and the point being made by the marlowe comment) is "inexperienced developers" and "experienced developers", and that question itself being differentiated on "haskell developers, or not", etc. 

I don't think we grow by not taking risks, but I also don't know whether catering to less experienced teams is the right route to a "killer app". I don't think there's a surplus of great ideas and deficit of beginner resources; I think there's a handful of passable-to-great ideas and a deficit of production-ready resources/tools that make it economical to build on Cardano even when you've got an experienced team (large or small)

we can't track correlation across responses. I think it would be very important to know, for example, the correlation between "years of experience writing and deploying software" and ranking "tough on-boarding, it's hard to get started".

There are 10 people who responded as having less than 1 year of experience writing software, and 15 who said on-boarding was their biggest pain point. 

If the former is a subset of the latter, thats a very different conclusion than if all 15 people who found it hard to get started had 10+ years of experience, but we can't know that from the data.

**Comment by KtorZ** [comment]
>  we can't track correlation across responses.

You actually can. The [raw data is available](https://github.com/cardano-foundation/state-of-the-developer-ecosystem/blob/main/2023/data/answers.json) on Github; answers are ordered. The 10th answer to the first question, 2nd questions and so on, comes from the same person. Some people did not answer until the end, so their answer will eventually all be "Not Answered" but are preserved to keep the correspondences. 

You are free to refine the analysis / report and comment. It's open source for this very reason. We have only little time to work on this, and we try to strike the right balance between useful and demanding. We could spend a month analyzing the data  and cross comparing results. We don't have a month.

**Comment by peter-mlabs** [comment]
Thanks @KtorZ, this is great!

**Comment by KtorZ** [comment]
I should probably mention that somewhere in the README or in a notice. I thought I did.

**Comment by aleeusgr** [comment]
around June maybe
